"use client";

import { ShoppingListItem } from "@/lib/types";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Checkbox } from "@/components/ui/checkbox";
import { Edit, Loader2, Trash, AlertTriangle, Bot } from "lucide-react";
import { useCurrency } from "@/lib/currency";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

interface ShoppingListTableProps {
  items: ShoppingListItem[];
  onEditItem: (item: ShoppingListItem) => void;
  onDeleteItem: (id: string) => Promise<void>;
  onTogglePurchased: (id: string, isPurchased: boolean) => Promise<void>;
  isDeleting: boolean;
  isUpdating: boolean;
}

export default function ShoppingListTable({
  items,
  onEditItem,
  onDeleteItem,
  onTogglePurchased,
  isDeleting,
  isUpdating,
}: ShoppingListTableProps) {
  const { formatCurrency } = useCurrency();

  if (items.length === 0) {
    return (
      <div className="flex h-[200px] items-center justify-center rounded-md border border-dashed">
        <p className="text-sm text-muted-foreground">
          No items in your shopping list
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-md border">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="w-[50px]">Status</TableHead>
            <TableHead>Name</TableHead>
            <TableHead>Quantity</TableHead>
            <TableHead>Category</TableHead>
            <TableHead className="text-right">Est. Cost</TableHead>
            <TableHead className="w-[100px]">Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {items.map((item) => (
            <TableRow
              key={item.id}
              className={cn(
                item.isPurchased && "bg-muted/50",
                item.isUrgent && !item.isPurchased && "bg-red-50/50"
              )}
            >
              <TableCell>
                <div className="flex items-center gap-2">
                  <Checkbox
                    checked={item.isPurchased}
                    onCheckedChange={(checked) =>
                      onTogglePurchased(item.id, checked as boolean)
                    }
                    disabled={isUpdating}
                  />
                  <div className="flex gap-1">
                    {item.isAutoGenerated && (
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger>
                            <Bot className="h-4 w-4 text-muted-foreground" />
                          </TooltipTrigger>
                          <TooltipContent>
                            Auto-generated from low stock
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                    )}
                    {item.isUrgent && !item.isPurchased && (
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger>
                            <AlertTriangle className="h-4 w-4 text-destructive" />
                          </TooltipTrigger>
                          <TooltipContent>
                            Urgent: Stock critically low
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                    )}
                  </div>
                </div>
              </TableCell>
              <TableCell className="font-medium">
                <div>
                  <span
                    className={cn(
                      item.isPurchased && "text-muted-foreground line-through"
                    )}
                  >
                    {item.name}
                  </span>
                  {item.notes && (
                    <p className="text-sm text-muted-foreground">
                      {item.notes}
                    </p>
                  )}
                  {item.inventoryItemId && (
                    <Badge variant="secondary" className="mt-1">
                      Linked to Inventory
                    </Badge>
                  )}
                </div>
              </TableCell>
              <TableCell>
                <span className="whitespace-nowrap">
                  {item.quantity} {item.unit}
                </span>
              </TableCell>
              <TableCell>
                <Badge variant="outline">{item.category}</Badge>
              </TableCell>
              <TableCell className="text-right">
                {formatCurrency(item.estimatedCost || 0)}
              </TableCell>
              <TableCell>
                <div className="flex items-center gap-2">
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => onEditItem(item)}
                    disabled={isDeleting || isUpdating}
                  >
                    <Edit className="h-4 w-4" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => onDeleteItem(item.id)}
                    disabled={isDeleting || isUpdating}
                  >
                    {isDeleting ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <Trash className="h-4 w-4" />
                    )}
                  </Button>
                </div>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
