/**
 * Application Types
 * 
 * These types are used throughout the application code.
 * They may transform database types to be more frontend-friendly.
 * 
 * Feel free to extend these types as needed for UI purposes.
 */

// ShoppingListItem for use in the application
export type ShoppingListItem = {
    id: string;
    inventoryItemId?: string; // camelCase version of inventory_item_id
    name: string;
    quantity: number;
    unit: string;
    estimatedCost: number; // camelCase version of estimated_cost
    category: string; // Made required for UI purposes
    notes?: string;
    isPurchased: boolean; // camelCase version of is_purchased
    isAutoGenerated: boolean; // camelCase version of is_auto_generated
    addedAt: string; // camelCase version of added_at
    purchasedAt?: string; // camelCase version of purchased_at
    userId?: string; // camelCase version of user_id
    businessProfileId?: string; // camelCase version of business_profile_id
};

// Add other application types as needed... 